### ISSUE TITLE
Broken bluetooth connections on Raspberry Pi 3 and Zero W

### ISSUE THREAD

**Issue by grover** [grover/homebridge-flower-sensor#1]
Raspberry Pi seems to have hardware issues talking to Flower Power/Pot devices. See:

* https://github.com/noble/noble/issues/764
* https://github.com/noble/noble/issues/751

And in the node-flower-power project:

* https://github.com/sandeepmistry/node-flower-power/issues/26

As of now I can't really do anything, but hope this gets resolved either with an update to Raspbian, a firmware update for the Broadcom chip used or a fix in noble.

In the mean time I'm trying if it works when using a USB Bluetooth Dongle.

**Comment by grover** [comment]
Use an external USB BLE Dongle. Raspberry Pi 3/Zero W onboard Bluetooth is unfortunately broken.

**Comment by capitainabloc** [comment]
I tried with a USB BLE dongle, with same poor result...

**Comment by AndyChoon** [comment]
> Use an external USB BLE Dongle. Raspberry Pi 3/Zero W onboard Bluetooth is unfortunately broken.

Hi @grover , do you have some USB BLE dongle to recommend? I brought one BLE USB dongle and used it on raspberry pi 3, when I try to connect the ble service, the BLEscanner on phone notified "Data is stale". I guess either the pybleno code running on pi3  cannot work with external adapter, or the USB dongle I brought doesn't support BLE.
